Ext.define('ProjetoGarage.model.orcamento.Produto', {
    extend: 'Ext.data.Model',
    fields: [{
        name: 'OrcamentoProdutoId',
        type: 'INT'
    }, {
        name: 'OrcamentoId',
        type: 'INT'
    }, {
        name: 'ProdutoId',
        type: 'INT'
    }, {
        name: 'Descricao',
        type: 'STRING'
    }, {
        name: 'UnidadeMedidaId',
        type: 'INT'
    }, {
        name: 'UnidadeMedidaNome',
        type: 'STRING'
    }, {
        name: 'Quantidade',
        type: 'FLOAT'
    }, {
        name: 'ValorUnitario',
        type: 'FLOAT'
    }, {
        name: 'ValorTotal',
        type: 'FLOAT'
    }, {
        name: 'Observacao',
        type: 'STRING'
    }, {
        name: 'UsuarioIdInclusao',
        type: 'INT',
        persist: false
    }, {
        name: 'UsuarioNomeInclusao',
        type: 'STRING',
        persist: false
    }, {
        name: 'DataHoraInclusao',
        type: 'DATE',
        persist: false
    }, {
        name: 'UsuarioIdAlteracao',
        type: 'INT',
        persist: false
    }, {
        name: 'UsuarioNomeAlteracao',
        type: 'STRING',
        persist: false
    }, {
        name: 'DataHoraAlteracao',
        type: 'DATE',
        persist: false
    }]
});