Ext.define('ProjetoGarage.model.funcionalidade.Model', {
    extend: 'Ext.data.Model',
    fields: [{
        name: 'FuncionalidadeId',
        type: 'INT'
    }, {
        name: 'Menu',
        type: 'STRING'
    }, {
        name: 'Titulo',
        type: 'STRING'
    }, {
        name: 'ClassName',
        type: 'STRING'
    }, {
        name: 'ModuloId',
        type: 'INT'
    }, {
        name: 'Modulo',
        type: 'STRING'
    }, {
        name: 'UsuarioIdInclusao',
        type: 'INT'
    }, {
        name: 'UsuarioNomeInclusao',
        type: 'STRING'
    }, {
        name: 'DataHoraInclusao',
        type: 'DATE'
    }, {
        name: 'UsuarioIdAlteracao',
        type: 'INT'
    }, {
        name: 'UsuarioNomeAlteracao',
        type: 'STRING'
    }, {
        name: 'DataHoraAlteracao',
        type: 'DATE'
    }]
});