Ext.define('ProjetoGarage.model.modelo.Model', {
    extend: 'Ext.data.Model',
    fields: [{
        name: 'ModeloId',
        type: 'INT'
    }, {
        name: 'MarcaId',
        type: 'INT'
    }, {
        name: 'Marca',
        type: 'STRING'
    }, {
        name: 'Nome',
        type: 'STRING'
    }, {
        name: 'UsuarioIdInclusao',
        type: 'INT'
    }, {
        name: 'UsuarioNomeInclusao',
        type: 'STRING'
    }, {
        name: 'DataHoraInclusao',
        type: 'DATE'
    }, {
        name: 'UsuarioIdAlteracao',
        type: 'INT'
    }, {
        name: 'UsuarioNomeAlteracao',
        type: 'STRING'
    }, {
        name: 'DataHoraAlteracao',
        type: 'DATE'
    }]
});