Ext.define('ProjetoGarage.model.veiculo.Model', {
    extend: 'Ext.data.Model',
    fields: [{
        name: 'VeiculoId',
        type: 'INT'
    }, {
        name: 'Placa',
        type: 'STRING'
    }, {
        name: 'ClienteId',
        type: 'INT'
    }, {
        name: 'Cliente',
        type: 'STRING'
    }, {
        name: 'MarcaId',
        type: 'INT'
    }, {
        name: 'Marca',
        type: 'STRING'
    }, {
        name: 'ModeloId',
        type: 'INT'
    }, {
        name: 'Modelo',
        type: 'STRING'
    }, {
        name: 'Ano',
        type: 'INT'
    }, {
        name: 'Cor',
        type: 'STRING'
    }, {
        name: 'Observacao',
        type: 'STRING'
    }, {
        name: 'UsuarioIdInclusao',
        type: 'INT'
    }, {
        name: 'UsuarioNomeInclusao',
        type: 'STRING'
    }, {
        name: 'DataHoraInclusao',
        type: 'DATE'
    }, {
        name: 'UsuarioIdAlteracao',
        type: 'INT'
    }, {
        name: 'UsuarioNomeAlteracao',
        type: 'STRING'
    }, {
        name: 'DataHoraAlteracao',
        type: 'DATE'
    }]
});