Ext.define('ProjetoGarage.model.contaPagar.Pagamento', {
    extend: 'Ext.data.Model',
    fields: [{
        name: 'ContaPagarDetalheId',
        type: 'INT'
    }, {
        name: 'ContaPagarId',
        type: 'INT'
    }, {
        name: 'Documento',
        type: 'STRING'
    }, {
        name: 'TipoPagamentoId',
        type: 'INT'
    }, {
        name: 'TipoPagamentoNome',
        type: 'STRING',
        persist: false
    }, {
        name: 'DataPagamento',
        type: 'DATE',
        serialize: function (v) {
            return Ext.Date.format(v, 'Y-m-d H:i:s');
        }
    }, {
        name: 'ValorPago',
        type: 'FLOAT'
    }, {
        name: 'Estornado',
        type: 'BOOL'
    }, {
        name: 'UsuarioIdInclusao',
        type: 'INT',
        persist: false
    }, {
        name: 'UsuarioNomeInclusao',
        type: 'STRING',
        persist: false
    }, {
        name: 'DataHoraInclusao',
        type: 'DATE',
        persist: false
    }, {
        name: 'UsuarioIdAlteracao',
        type: 'INT',
        persist: false
    }, {
        name: 'UsuarioNomeAlteracao',
        type: 'STRING',
        persist: false
    }, {
        name: 'DataHoraAlteracao',
        type: 'DATE',
        persist: false
    }, {
        name: 'DataPreenchimentoTela',
        type: 'DATE'
    }]
});